# Generated by Django 3.0.6 on 2020-05-24 21:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='тип опроса', max_length=200, unique=True)),
                ('type', models.CharField(choices=[('A', 'On-Off'), ('O', 'One from all'), ('M', 'Many from all')], help_text='тип системы', max_length=1)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('another', models.BooleanField(default=False, help_text='Есть другое')),
                ('another_text', models.BooleanField(default=False, help_text='поле текста если выбрано другое')),
                ('state', models.CharField(choices=[('E', 'Enable'), ('D', 'Disable'), ('A', 'Archived')], default='E', help_text='состояние', max_length=1)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Время создания опроса')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_polls', to='dashboard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Sharetext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='текст для расшаривания опроса', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Время опроса пользователем')),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('input_text', models.CharField(blank=True, help_text='текст со своим вариантом', max_length=200, null=True)),
                ('session_key', models.CharField(help_text='request.session.session_key', max_length=200)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_polls', to='dashboard.Poll')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='share_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_polls', to='dashboard.Sharetext'),
        ),
    ]
