# Generated by Django 3.0.6 on 2020-05-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('dashboard', '0003_poll_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='session_key',
            field=models.ForeignKey(help_text='request.session.session_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.Session'),
        ),
    ]
